### ISSUE TITLE
Add Katana to your comparison

### ISSUE THREAD

**Issue by svenjacobs** [Sloy/android-dependency-injection-performance#1]
I'm curious to know how [Katana](https://github.com/rewe-digital-incubator/katana) compares to the other DI libraries in your test. I did my own [performance test](https://github.com/rewe-digital-incubator/katana/tree/master/speed-comparison) and Katana was the fastest compared to Koin and Kodein.

**Comment by svenjacobs** [comment]
Please see #2

**Comment by Sloy** [comment]
Great idea, and great contribution. Thanks!

**Comment by Sloy** [comment]
Results with Katana are now published in the Readme :)

**Comment by svenjacobs** [comment]
Nice! 👌 Thank you!
